name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI or Anthropic API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT (required if using OpenAI)."
    required: false
  ANTHROPIC_API_KEY:
    description: "Anthropic API key for Claude (required if using Anthropic)."
    required: false
  AI_PROVIDER:
    description: "AI provider to use (openai or anthropic)"
    required: false
    default: "openai"
  OPENAI_API_MODEL:
    description: "OpenAI API model (only used if AI_PROVIDER is openai)."
    required: false
    default: "gpt-4o"
  ANTHROPIC_API_MODEL:
    description: "Anthropic API model (only used if AI_PROVIDER is anthropic)."
    required: false
    default: "claude-3-5-sonnet-20241022"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  role:
    description: "AI's role eg: senior android developer"
    required: false
    default: "senior developer"
  tech_stack:
    description: "Project's tech stack to pass to AI"
    required: false
    default: ""
  pr_ignore:
    description: ".prignore file to list things to exclude from review"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
